/**
 * Seeds the plant catalog with vegetables, herbs and berries commonly grown in
 * Lithuania, along with local sowing and harvest windows (month numbers).
 *
 * Idempotent: run `npm run db:seed` as often as you like.
 */
// Env comes from `node --env-file-if-exists=.env.local` in the db:seed script.
// Loading it here would be too late: ESM evaluates imports before statements,
// so ./index would build its connection pool against an empty DATABASE_URL.
import { db } from "./index";
import { plantCatalog } from "./schema";

type CatalogSeed = typeof plantCatalog.$inferInsert;

const CATALOG: CatalogSeed[] = [
  // Nightshades
  {
    nameLt: "Pomidorai",
    nameEn: "Tomato",
    latinName: "Solanum lycopersicum",
    family: "nightshade",
    spacingCm: 50,
    daysToMaturity: 100,
    sowFromMonth: 3,
    sowToMonth: 4,
    harvestFromMonth: 7,
    harvestToMonth: 9,
    careNotesLt:
      "Auginti daigus namuose, į lauką sodinti po šalnų. Rišti prie atramų, laistyti po šaknimis.",
    careNotesEn: "Start indoors, plant out after the last frost. Stake and water at the root.",
  },
  {
    nameLt: "Bulvės",
    nameEn: "Potato",
    latinName: "Solanum tuberosum",
    family: "nightshade",
    spacingCm: 35,
    daysToMaturity: 110,
    sowFromMonth: 4,
    sowToMonth: 5,
    harvestFromMonth: 7,
    harvestToMonth: 9,
    careNotesLt: "Sodinti daigintus gumbus. Kaupti 2 kartus per sezoną.",
    careNotesEn: "Plant chitted tubers. Earth up twice during the season.",
  },
  {
    nameLt: "Paprikos",
    nameEn: "Sweet pepper",
    latinName: "Capsicum annuum",
    family: "nightshade",
    spacingCm: 40,
    daysToMaturity: 120,
    sowFromMonth: 2,
    sowToMonth: 3,
    harvestFromMonth: 7,
    harvestToMonth: 9,
    careNotesLt: "Šiltnamyje derlius gerokai didesnis. Mėgsta šilumą ir reguliarų laistymą.",
    careNotesEn: "Much better under glass. Likes warmth and steady watering.",
  },
  {
    nameLt: "Baklažanai",
    nameEn: "Aubergine",
    latinName: "Solanum melongena",
    family: "nightshade",
    spacingCm: 45,
    daysToMaturity: 130,
    sowFromMonth: 2,
    sowToMonth: 3,
    harvestFromMonth: 8,
    harvestToMonth: 9,
    careNotesLt: "Tik šiltnamiui. Reikia daug šilumos ir šviesos.",
    careNotesEn: "Greenhouse only in this climate. Needs plenty of heat and light.",
  },

  // Leafy greens
  {
    nameLt: "Salotos",
    nameEn: "Lettuce",
    latinName: "Lactuca sativa",
    family: "leafy",
    spacingCm: 25,
    daysToMaturity: 55,
    sowFromMonth: 4,
    sowToMonth: 8,
    harvestFromMonth: 5,
    harvestToMonth: 10,
    careNotesLt:
      "Sėti kas 2–3 savaites, kad derlius būtų nuolatinis. Karštu metu mėgsta pusiau pavėsį.",
    careNotesEn: "Sow every 2–3 weeks for a steady supply. Appreciates part shade in high summer.",
  },
  {
    nameLt: "Špinatai",
    nameEn: "Spinach",
    latinName: "Spinacia oleracea",
    family: "leafy",
    spacingCm: 15,
    daysToMaturity: 45,
    sowFromMonth: 4,
    sowToMonth: 8,
    harvestFromMonth: 5,
    harvestToMonth: 10,
    careNotesLt: "Vėsų orą mėgstantis augalas. Karštyje greitai išleidžia žiedstiebius.",
    careNotesEn: "A cool-weather crop; bolts quickly in the heat.",
  },
  {
    nameLt: "Rukola",
    nameEn: "Rocket",
    latinName: "Eruca vesicaria",
    family: "leafy",
    spacingCm: 15,
    daysToMaturity: 40,
    sowFromMonth: 4,
    sowToMonth: 9,
    harvestFromMonth: 5,
    harvestToMonth: 10,
    careNotesLt: "Greitai auga. Skinti jaunus lapus — seni būna aitrūs.",
    careNotesEn: "Fast growing. Pick young leaves; older ones turn harsh.",
  },
  {
    nameLt: "Mangoldas",
    nameEn: "Chard",
    latinName: "Beta vulgaris subsp. cicla",
    family: "leafy",
    spacingCm: 30,
    daysToMaturity: 60,
    sowFromMonth: 4,
    sowToMonth: 6,
    harvestFromMonth: 6,
    harvestToMonth: 10,
    careNotesLt: "Skinti išorinius lapus — augalas augs visą sezoną.",
    careNotesEn: "Pick the outer leaves and the plant keeps producing all season.",
  },

  // Root vegetables
  {
    nameLt: "Morkos",
    nameEn: "Carrot",
    latinName: "Daucus carota",
    family: "root",
    spacingCm: 5,
    daysToMaturity: 90,
    sowFromMonth: 4,
    sowToMonth: 6,
    harvestFromMonth: 7,
    harvestToMonth: 10,
    careNotesLt:
      "Reikia purios, akmenų neturinčios dirvos. Retinti daigus, kitaip šaknys būna smulkios.",
    careNotesEn: "Needs loose, stone-free soil. Thin the seedlings or the roots stay small.",
  },
  {
    nameLt: "Burokėliai",
    nameEn: "Beetroot",
    latinName: "Beta vulgaris",
    family: "root",
    spacingCm: 10,
    daysToMaturity: 95,
    sowFromMonth: 4,
    sowToMonth: 6,
    harvestFromMonth: 7,
    harvestToMonth: 10,
    careNotesLt: "Lapai taip pat valgomi. Nuimti prieš pirmąsias šalnas.",
    careNotesEn: "The leaves are edible too. Lift before the first frosts.",
  },
  {
    nameLt: "Ridikėliai",
    nameEn: "Radish",
    latinName: "Raphanus sativus",
    family: "root",
    spacingCm: 5,
    daysToMaturity: 28,
    sowFromMonth: 4,
    sowToMonth: 8,
    harvestFromMonth: 5,
    harvestToMonth: 9,
    careNotesLt: "Greičiausias derlius darže. Sausroje pasidaro aitrūs ir kietėja.",
    careNotesEn: "The quickest crop in the garden. Turns hot and woody if left dry.",
  },
  {
    nameLt: "Pastarnokai",
    nameEn: "Parsnip",
    latinName: "Pastinaca sativa",
    family: "root",
    spacingCm: 15,
    daysToMaturity: 140,
    sowFromMonth: 4,
    sowToMonth: 5,
    harvestFromMonth: 9,
    harvestToMonth: 11,
    careNotesLt: "Skonis pagerėja po pirmųjų šalnų.",
    careNotesEn: "The flavour improves after the first frost.",
  },
  {
    nameLt: "Salierai",
    nameEn: "Celeriac",
    latinName: "Apium graveolens",
    family: "root",
    spacingCm: 35,
    daysToMaturity: 150,
    sowFromMonth: 2,
    sowToMonth: 3,
    harvestFromMonth: 9,
    harvestToMonth: 10,
    careNotesLt: "Ilgas vegetacijos periodas — būtini daigai. Mėgsta drėgmę.",
    careNotesEn: "A long season, so start with transplants. Likes consistent moisture.",
  },

  // Brassicas
  {
    nameLt: "Baltagūžiai kopūstai",
    nameEn: "White cabbage",
    latinName: "Brassica oleracea var. capitata",
    family: "brassica",
    spacingCm: 45,
    daysToMaturity: 110,
    sowFromMonth: 3,
    sowToMonth: 5,
    harvestFromMonth: 7,
    harvestToMonth: 10,
    careNotesLt: "Saugoti nuo kopūstinių baltukų — padeda tinklelis. Nesodinti po kitų kopūstinių.",
    careNotesEn: "Net against cabbage white butterflies. Do not follow other brassicas.",
  },
  {
    nameLt: "Brokoliai",
    nameEn: "Broccoli",
    latinName: "Brassica oleracea var. italica",
    family: "brassica",
    spacingCm: 45,
    daysToMaturity: 95,
    sowFromMonth: 3,
    sowToMonth: 6,
    harvestFromMonth: 7,
    harvestToMonth: 10,
    careNotesLt: "Nupjovus centrinę galvutę, išauga šoninės.",
    careNotesEn: "Cut the main head and side shoots follow.",
  },
  {
    nameLt: "Žiediniai kopūstai",
    nameEn: "Cauliflower",
    latinName: "Brassica oleracea var. botrytis",
    family: "brassica",
    spacingCm: 50,
    daysToMaturity: 100,
    sowFromMonth: 3,
    sowToMonth: 5,
    harvestFromMonth: 7,
    harvestToMonth: 10,
    careNotesLt: "Norint baltos galvutės, uždengti ją lapais.",
    careNotesEn: "Fold leaves over the curd to keep it white.",
  },
  {
    nameLt: "Kaliaropės",
    nameEn: "Kohlrabi",
    latinName: "Brassica oleracea var. gongylodes",
    family: "brassica",
    spacingCm: 25,
    daysToMaturity: 60,
    sowFromMonth: 4,
    sowToMonth: 7,
    harvestFromMonth: 6,
    harvestToMonth: 10,
    careNotesLt: "Nuimti, kol nesumedėjo — apie 7–8 cm skersmens.",
    careNotesEn: "Harvest before it turns woody, at about 7–8 cm across.",
  },
  {
    nameLt: "Ropės",
    nameEn: "Turnip",
    latinName: "Brassica rapa",
    family: "brassica",
    spacingCm: 15,
    daysToMaturity: 60,
    sowFromMonth: 4,
    sowToMonth: 7,
    harvestFromMonth: 6,
    harvestToMonth: 10,
    careNotesLt: "Sėti tiesiai į gruntą. Mėgsta vėsų orą.",
    careNotesEn: "Sow direct. Prefers cool weather.",
  },

  // Alliums
  {
    nameLt: "Svogūnai",
    nameEn: "Onion",
    latinName: "Allium cepa",
    family: "allium",
    spacingCm: 12,
    daysToMaturity: 120,
    sowFromMonth: 4,
    sowToMonth: 5,
    harvestFromMonth: 8,
    harvestToMonth: 9,
    careNotesLt: "Sodinti sėjinukus. Prieš nuimant nutraukti laistymą.",
    careNotesEn: "Plant sets. Stop watering shortly before lifting.",
  },
  {
    nameLt: "Česnakai",
    nameEn: "Garlic",
    latinName: "Allium sativum",
    family: "allium",
    spacingCm: 15,
    daysToMaturity: 240,
    sowFromMonth: 9,
    sowToMonth: 10,
    harvestFromMonth: 7,
    harvestToMonth: 8,
    careNotesLt: "Žieminiai česnakai sodinami rudenį ir nuimami kitą vasarą. Nulaužti strėles.",
    careNotesEn: "Autumn-planted hardneck garlic is lifted the next summer. Snap off the scapes.",
  },
  {
    nameLt: "Porai",
    nameEn: "Leek",
    latinName: "Allium ampeloprasum",
    family: "allium",
    spacingCm: 20,
    daysToMaturity: 150,
    sowFromMonth: 3,
    sowToMonth: 4,
    harvestFromMonth: 9,
    harvestToMonth: 11,
    careNotesLt: "Kaupti, kad stiebas išbaltų. Atlaiko lengvas šalnas.",
    careNotesEn: "Earth up to blanch the stems. Stands light frost.",
  },
  {
    nameLt: "Laiškiniai svogūnai",
    nameEn: "Chives",
    latinName: "Allium schoenoprasum",
    family: "allium",
    spacingCm: 20,
    daysToMaturity: 60,
    sowFromMonth: 4,
    sowToMonth: 6,
    harvestFromMonth: 5,
    harvestToMonth: 10,
    careNotesLt: "Daugiametis. Kas kelerius metus dalinti kerelius.",
    careNotesEn: "Perennial. Divide the clumps every few years.",
  },

  // Legumes
  {
    nameLt: "Žirniai",
    nameEn: "Pea",
    latinName: "Pisum sativum",
    family: "legume",
    spacingCm: 8,
    daysToMaturity: 70,
    sowFromMonth: 4,
    sowToMonth: 6,
    harvestFromMonth: 6,
    harvestToMonth: 8,
    careNotesLt: "Reikia atramų. Kaupia azotą dirvoje — geras priešsėlis.",
    careNotesEn: "Needs support. Fixes nitrogen, so a good crop to precede others.",
  },
  {
    nameLt: "Pupelės",
    nameEn: "Bean",
    latinName: "Phaseolus vulgaris",
    family: "legume",
    spacingCm: 20,
    daysToMaturity: 75,
    sowFromMonth: 5,
    sowToMonth: 6,
    harvestFromMonth: 7,
    harvestToMonth: 9,
    careNotesLt: "Sėti tik praėjus šalnoms — jautrios šalčiui.",
    careNotesEn: "Sow only after the frosts; they are frost tender.",
  },
  {
    nameLt: "Pupos",
    nameEn: "Broad bean",
    latinName: "Vicia faba",
    family: "legume",
    spacingCm: 20,
    daysToMaturity: 90,
    sowFromMonth: 3,
    sowToMonth: 5,
    harvestFromMonth: 6,
    harvestToMonth: 8,
    careNotesLt: "Atsparios vėsai, sėti anksti. Stebėti amarus viršūnėse.",
    careNotesEn: "Hardy, so sow early. Watch for blackfly on the tips.",
  },

  // Cucurbits
  {
    nameLt: "Agurkai",
    nameEn: "Cucumber",
    latinName: "Cucumis sativus",
    family: "cucurbit",
    spacingCm: 40,
    daysToMaturity: 60,
    sowFromMonth: 4,
    sowToMonth: 6,
    harvestFromMonth: 7,
    harvestToMonth: 9,
    careNotesLt: "Laistyti šiltu vandeniu. Rinkti dažnai, kad augtų nauji.",
    careNotesEn: "Water with warm water. Pick often to keep new fruit coming.",
  },
  {
    nameLt: "Cukinijos",
    nameEn: "Courgette",
    latinName: "Cucurbita pepo",
    family: "cucurbit",
    spacingCm: 90,
    daysToMaturity: 55,
    sowFromMonth: 5,
    sowToMonth: 6,
    harvestFromMonth: 7,
    harvestToMonth: 9,
    careNotesLt: "Užima daug vietos. Rinkti jaunas — 15–20 cm.",
    careNotesEn: "Takes a lot of room. Pick young, at 15–20 cm.",
  },
  {
    nameLt: "Moliūgai",
    nameEn: "Pumpkin",
    latinName: "Cucurbita maxima",
    family: "cucurbit",
    spacingCm: 120,
    daysToMaturity: 120,
    sowFromMonth: 5,
    sowToMonth: 6,
    harvestFromMonth: 9,
    harvestToMonth: 10,
    careNotesLt: "Nuimti prieš šalnas, palikti kotelį. Prieš sandėliuojant pavytinti.",
    careNotesEn: "Cut before frost leaving the stalk on, then cure before storing.",
  },

  // Herbs
  {
    nameLt: "Krapai",
    nameEn: "Dill",
    latinName: "Anethum graveolens",
    family: "herb",
    spacingCm: 15,
    daysToMaturity: 45,
    sowFromMonth: 4,
    sowToMonth: 7,
    harvestFromMonth: 5,
    harvestToMonth: 9,
    careNotesLt: "Sėti tiesiai į vietą — nemėgsta persodinimo. Lengvai pasisėja pats.",
    careNotesEn: "Sow where it will grow; it dislikes transplanting and self-seeds happily.",
  },
  {
    nameLt: "Petražolės",
    nameEn: "Parsley",
    latinName: "Petroselinum crispum",
    family: "herb",
    spacingCm: 20,
    daysToMaturity: 75,
    sowFromMonth: 3,
    sowToMonth: 6,
    harvestFromMonth: 6,
    harvestToMonth: 10,
    careNotesLt: "Sėklos dygsta lėtai — iki 3 savaičių. Dvimetis augalas.",
    careNotesEn: "Slow to germinate — up to three weeks. Biennial.",
  },
  {
    nameLt: "Bazilikas",
    nameEn: "Basil",
    latinName: "Ocimum basilicum",
    family: "herb",
    spacingCm: 20,
    daysToMaturity: 60,
    sowFromMonth: 4,
    sowToMonth: 6,
    harvestFromMonth: 6,
    harvestToMonth: 9,
    careNotesLt: "Mėgsta šilumą — geriausiai auga šiltnamyje ar ant palangės.",
    careNotesEn: "Wants warmth — best in a greenhouse or on a windowsill.",
  },
  {
    nameLt: "Mėtos",
    nameEn: "Mint",
    latinName: "Mentha",
    family: "herb",
    spacingCm: 30,
    daysToMaturity: 60,
    sowFromMonth: 4,
    sowToMonth: 6,
    harvestFromMonth: 5,
    harvestToMonth: 10,
    careNotesLt: "Labai plinta — sodinti į vazoną, įkastą į lysvę.",
    careNotesEn: "Spreads aggressively — plant in a sunken pot.",
  },
  {
    nameLt: "Čiobreliai",
    nameEn: "Thyme",
    latinName: "Thymus vulgaris",
    family: "herb",
    spacingCm: 25,
    daysToMaturity: 90,
    sowFromMonth: 4,
    sowToMonth: 6,
    harvestFromMonth: 6,
    harvestToMonth: 9,
    careNotesLt: "Mėgsta sausą, saulėtą vietą. Nepakenčia šlapios dirvos.",
    careNotesEn: "Wants a dry, sunny spot. Hates wet soil.",
  },

  // Berries
  {
    nameLt: "Braškės",
    nameEn: "Strawberry",
    latinName: "Fragaria × ananassa",
    family: "berry",
    spacingCm: 30,
    daysToMaturity: 365,
    sowFromMonth: 8,
    sowToMonth: 9,
    harvestFromMonth: 6,
    harvestToMonth: 7,
    careNotesLt:
      "Sodinti rudenį arba anksti pavasarį. Mulčiuoti šiaudais, atnaujinti kas 3–4 metus.",
    careNotesEn: "Plant in autumn or early spring. Mulch with straw and renew every 3–4 years.",
  },
  {
    nameLt: "Avietės",
    nameEn: "Raspberry",
    latinName: "Rubus idaeus",
    family: "berry",
    spacingCm: 50,
    daysToMaturity: 365,
    sowFromMonth: 10,
    sowToMonth: 11,
    harvestFromMonth: 7,
    harvestToMonth: 9,
    careNotesLt: "Reikia atramų. Vasarinėms veislėms po derliaus išpjauti derėjusias atžalas.",
    careNotesEn: "Needs support. For summer varieties, cut out the fruited canes after picking.",
  },
  {
    nameLt: "Juodieji serbentai",
    nameEn: "Blackcurrant",
    latinName: "Ribes nigrum",
    family: "berry",
    spacingCm: 150,
    daysToMaturity: 365,
    sowFromMonth: 10,
    sowToMonth: 11,
    harvestFromMonth: 7,
    harvestToMonth: 8,
    careNotesLt: "Kasmet išpjauti seniausias šakas — derlius auga ant jaunų.",
    careNotesEn: "Remove the oldest branches each year; fruit comes on young wood.",
  },
  {
    nameLt: "Agrastai",
    nameEn: "Gooseberry",
    latinName: "Ribes uva-crispa",
    family: "berry",
    spacingCm: 150,
    daysToMaturity: 365,
    sowFromMonth: 10,
    sowToMonth: 11,
    harvestFromMonth: 7,
    harvestToMonth: 8,
    careNotesLt: "Retinti krūmo vidų, kad būtų daugiau oro ir mažiau miltligės.",
    careNotesEn: "Open up the centre of the bush for airflow and less mildew.",
  },
  {
    nameLt: "Šilauogės",
    nameEn: "Blueberry",
    latinName: "Vaccinium corymbosum",
    family: "berry",
    spacingCm: 120,
    daysToMaturity: 365,
    sowFromMonth: 4,
    sowToMonth: 5,
    harvestFromMonth: 7,
    harvestToMonth: 9,
    careNotesLt: "Būtina rūgšti dirva (pH 4–5). Mulčiuoti spygliais ar durpėmis.",
    careNotesEn: "Needs acidic soil (pH 4–5). Mulch with pine needles or peat.",
  },

  // Other
  {
    nameLt: "Rabarbarai",
    nameEn: "Rhubarb",
    latinName: "Rheum rhabarbarum",
    family: "other",
    spacingCm: 100,
    daysToMaturity: 365,
    sowFromMonth: 10,
    sowToMonth: 11,
    harvestFromMonth: 5,
    harvestToMonth: 6,
    careNotesLt: "Pirmais metais neskinti. Lapai nuodingi — valgomi tik stiebai.",
    careNotesEn: "Do not pick in the first year. The leaves are toxic — stalks only.",
  },
  {
    nameLt: "Krienai",
    nameEn: "Horseradish",
    latinName: "Armoracia rusticana",
    family: "other",
    spacingCm: 60,
    daysToMaturity: 200,
    sowFromMonth: 4,
    sowToMonth: 5,
    harvestFromMonth: 9,
    harvestToMonth: 11,
    careNotesLt: "Labai plinta — riboti augimo vietą. Kasti vėlai rudenį.",
    careNotesEn: "Very invasive — confine it. Dig the roots in late autumn.",
  },
  {
    nameLt: "Cukriniai kukurūzai",
    nameEn: "Sweetcorn",
    latinName: "Zea mays",
    family: "other",
    spacingCm: 35,
    daysToMaturity: 100,
    sowFromMonth: 5,
    sowToMonth: 6,
    harvestFromMonth: 8,
    harvestToMonth: 9,
    careNotesLt: "Sodinti bloku, ne eile — apdulkina vėjas.",
    careNotesEn: "Plant in a block rather than a row — it is wind pollinated.",
  },
];

async function seed() {
  console.log(`Seeding ${CATALOG.length} plant catalog entries…`);

  for (const entry of CATALOG) {
    await db
      .insert(plantCatalog)
      .values(entry)
      .onConflictDoUpdate({ target: plantCatalog.nameLt, set: entry });
  }

  console.log("Done.");
  process.exit(0);
}

seed().catch((error) => {
  console.error(error);
  process.exit(1);
});
